# Reference Material
#
# * https://www.podcast.co/create/podcast-rss-feeds

title = "Chats with James Podcast"
description = """
Chats with James is a podcast discussing everything \
that James or his guests are passionate about.

Embedded Systems, the Rust Programming Language, and \
a variety of other technical topics are the most commonly \
discussed items.
"""
subtitle = "James Munns talks to guests about things they are passionate about"
website = "https://jamesmunns.com/podcast/"
language = "en-us"
copyright = "2020"
webmaster = "contact@onevariable.com (James Munns)"
managing-editor = "contact@onevariable.com (James Munns)"

author = "James Munns"
author-email = "contact@onevariable.com"

formats = [
    "flac",
    "mp3",
    "m4a",
]
hosting-base-url = "https://delivery.jamescdn.com"
explicit = false
keywords = [
    "rust",
    "programming",
    "technology"
]

# TODO - support subcategories?
category = "Technology"

[logo]
url = "https://delivery.jamescdn.com/logo2.png"
title = "Chats with James Podcast"
link = "https://jamesmunns.com/podcast/"

[[episodes]]
title = "016 - Scott Mabin"
url = "https://jamesmunns.com/podcast/016-scott/"
description = """
James talks with Scott Mabin about how he joined the Espressif team and got \
involved in embedded Rust, the working culture in chip manufacturing companies \
and preferences about designing and building mechanical keyboards.
"""
subtitle = "James chats with Scott Mabin"
files = [
    "2023-12-01-scott-mabin.mp3",
    "2023-12-01-scott-mabin.m4a",
    "2023-12-01-scott-mabin.flac",
]
duration = "00:52:56"
publish-date = "Fri, 1 Dec 2023 12:00:00 GMT"
keywords = [
    "programming",
    "technology",
    "Rust",
    "embedded",
]

[[episodes]]
title = "015 - Manish Goregaokar"
url = "https://jamesmunns.com/podcast/015-manish/"
description = """
Another episode is coming from the archives, originally recorded in May 2022 \
with Manish Goregaokar as the guest- James and Manish touch on many topics, \
including: internationalization of languages, zero-copy deserialization in \
Rust, speedrunning video games and Vaccinate CA.
"""
subtitle = "James chats with Manish Goregaokar"
files = [
    "2023-11-15-manish-goregaokar.mp3",
    "2023-11-15-manish-goregaokar.m4a",
    "2023-11-15-manish-goregaokar.flac",
]
duration = "01:05:48"
publish-date = "Wed, 15 Nov 2023 11:00:00 GMT"
keywords = [
    "programming",
    "technology",
    "Rust",
    "embedded",
]


[[episodes]]
title = "014 - Steve Klabnik"
url = "https://jamesmunns.com/podcast/014-steve/"
description = """
This episode is coming from the archives, originally recorded in May 2022 - \
James talks with Steve Klabnik from Oxide Computer about knowledge transfer \
within the Rust community, how learning-by-doing and reading datasheets help \
you develop, and how limits and regulations are put in place across many \
different fields.
"""
subtitle = "James chats with Steve Klabnik"
files = [
    "2023-09-29-steve-klabnik.mp3",
    "2023-09-29-steve-klabnik.m4a",
    "2023-09-29-steve-klabnik.flac",
]
duration = "01:34:39"
publish-date = "Fri, 29 Sep 2023 20:00:00 GMT"
keywords = [
    "programming",
    "technology",
    "Rust",
    "embedded",
]

[[episodes]]
title = "013 - Ryan Summers"
url = "https://jamesmunns.com/podcast/013-ryan/"
description = """
In this episode, James chats with Ryan Summers about the process of \
developing protocols, the guidelines of working in safety critical \
systems and embedded engineering.
"""
subtitle = "James chats with Ryan Summers"
files = [
    "2023-08-18-ryan-summers.mp3",
    "2023-08-18-ryan-summers.m4a",
    "2023-08-18-ryan-summers.flac",
]
duration = "01:20:28"
publish-date = "Fri, 18 Aug 2023 20:00:00 GMT"
keywords = [
    "programming",
    "technology",
    "Rust",
    "embedded",
]

[[episodes]]
title = "012 - Sophia Turner"
url = "https://jamesmunns.com/podcast/012-sophia-turner/"
description = """
In this episode, James chats with Sophia about the intricacies of writing \
programming languages, what makes designing programs fun, strategies \
for defining goals, and more.
"""
subtitle = "James chats with Sophia Turner"
# NOTE: we did not rename the files as we use filenames as the GUID, and could
# potentially cause problems
files = [
    "2023-07-17-JT.mp3",
    "2023-07-17-JT.m4a",
    "2023-07-17-JT.flac",
]
duration = "01:02:21"
publish-date = "Mon, 17 Jul 2023 20:00:00 GMT"
keywords = [
    "programming",
    "technology",
    "Rust",
    "embedded",
]

[[episodes]]
title = "011 - Eliza Weisman"
url = "https://jamesmunns.com/podcast/011-eliza/"
description = """
James chats with Eliza about systems, systems of systems, operating \
systems, java, java cards, what posix did wrong, and a ton of other \
rust adjacent things.
"""
subtitle = "James chats with Eliza Weisman"
files = [
    "2022-04-12-eliza-weisman.mp3",
    "2022-04-12-eliza-weisman.m4a",
    "2022-04-12-eliza-weisman.flac",
]
duration = "01:59:44"
publish-date = "Tue, 12 Apr 2022 22:00:00 GMT"
keywords = [
    "programming",
    "technology",
    "Rust",
    "embedded",
]

[[episodes]]
title = "010 - Dion Dokter"
url = "https://jamesmunns.com/podcast/010-dion/"
description = """
James chats with Dion Dokter about device drivers, bootloaders, \
and embedded Rust.
"""
subtitle = "James chats with Dion Dokter"
files = [
    "2021-03-02-dion-doktor.m4a",
    "2021-03-02-dion-doktor.mp3",
    "2021-03-02-dion-doktor.flac",
]
duration = "00:35:50"
publish-date = "Tue, 02 Mar 2021 22:00:00 GMT"
keywords = [
    "programming",
    "technology",
    "Rust",
    "embedded",
]


[[episodes]]
title = "009 - Sylvan Morris"
url = "https://jamesmunns.com/podcast/009-sylvan/"
description = """
James chats with Sylvan Morris about introducing Rust into a company, \
working at an embedded startup, over the air bootloaders, and managing risk.
"""
subtitle = "James chats with Sylvan Morris"
files = [
    "2021-02-23-sylvan-morris.m4a",
    "2021-02-23-sylvan-morris.mp3",
    "2021-02-23-sylvan-morris.flac",
]
duration = "00:27:44"
publish-date = "Tue, 23 Feb 2021 23:59:00 GMT"
keywords = [
    "programming",
    "technology",
    "engineering",
    "Rust",
    "risk",
    "start-ups",
    "embedded",
]

[[episodes]]
title = "008 - Yoshua Wuyts"
url = "https://jamesmunns.com/podcast/008-yosh/"
description = """
James chats with Yoshua Wuyts to discuss Control Theory in traditional software domains, the \
possibilities of RISC-V, and open source hardware.
"""
subtitle = "James chats with Yoshua Wuyts"
files = [
    "2021-02-16-yoshua-wuyts.m4a",
    "2021-02-16-yoshua-wuyts.mp3",
    "2021-02-16-yoshua-wuyts.flac",
]
duration = "00:53:18"
publish-date = "Tue, 16 Feb 2021 21:00:00 GMT"
keywords = [
    "programming",
    "technology",
    "engineering",
    "Rust",
    "control systems",
    "risc-v",
]

[[episodes]]
title = "007 - Michael Nitschinger"
url = "https://jamesmunns.com/podcast/007-michael/"
description = """
James chats with Michael Nitschinger of Couchbase to discuss Coffee \
Machines, PID control loops, Bluetooth Low Energy, and Databases.
"""
subtitle = "James chats with Michael Nitschinger of Couchbase"
files = [
    "2021-02-09-michael-nitschinger.m4a",
    "2021-02-09-michael-nitschinger.mp3",
    "2021-02-09-michael-nitschinger.flac",
]
duration = "00:53:08"
publish-date = "Tue, 09 Feb 2021 11:00:00 GMT"
keywords = [
    "programming",
    "technology",
    "engineering",
    "Rust",
    "coffee",
    "espresso",
    "control systems",
    "databases",
]

[[episodes]]
title = "006 - Bryan Cantrill"
url = "https://jamesmunns.com/podcast/006-bryan/"
description = """
James chats with Bryan Cantrill of Oxide Computer to discuss the \
open source hardware explosion, Oxide's experience with Embedded Rust, \
the importance of a culture of sharing knowledge, and the joy of fixing \
hard-to-diagnose systems problems.
"""
subtitle = "James chats with Bryan Cantrill of Oxide Computer Company"
files = [
    "2021-02-02-bryan-cantrill.m4a",
    "2021-02-02-bryan-cantrill.mp3",
    "2021-02-02-bryan-cantrill.flac",
]
duration = "01:24:22"
publish-date = "Tue, 02 Feb 2021 16:00:00 GMT"
keywords = [
    "programming",
    "technology",
    "engineering",
    "Rust",
    "systems engineering",
    "open source",
]

[[episodes]]
title = "005 - Clifford Heath"
url = "https://jamesmunns.com/podcast/005-clifford/"
description = """
James chats with Clifford Heath to \
discuss the differences between procedural and structural code, using \
natural language processing to describe software, code generation, \
and programming education approaches.
"""
subtitle = "James chats with Clifford Heath"
files = [
    "2021-01-26-clifford-heath.m4a",
    "2021-01-26-clifford-heath.mp3",
    "2021-01-26-clifford-heath.flac",
]
duration = "01:04:45"
publish-date = "Tue, 26 Jan 2021 14:00:00 GMT"
keywords = [
    "programming",
    "technology",
    "engineering",
    "schemas",
    "natural language",
]

[[episodes]]
title = "004 - François Baldassari"
url = "https://jamesmunns.com/podcast/004-francois/"
description = """
James chats with François Baldassari to discuss embedded systems, \
engineering practices (and where the industry is lacking), and the \
social side of improving the skills of embedded systems teams.
"""
subtitle = "James chats with François Baldassari of Memfault"
files = [
    "2021-01-19-francois-baldassari.m4a",
    "2021-01-19-francois-baldassari.mp3",
    "2021-01-19-francois-baldassari.flac",
]
duration = "00:48:36"
publish-date = "Tue, 19 Jan 2021 06:00:00 GMT"
keywords = [
    "programming",
    "technology",
    "embedded",
    "embedded systems",
    "software quality",
    "engineering",
]

[[episodes]]
title = "003 - Michael Gattozzi"
url = "https://jamesmunns.com/podcast/003-michael/"
description = """
James chats with Michael Gattozzi to discuss developer tooling, message \
serialization, and undefined behavior in Rust.
"""
subtitle = "James chats with Michael Gattozzi"
files = [
    "2021-01-12-michael-gattozzi.m4a",
    "2021-01-12-michael-gattozzi.mp3",
    "2021-01-12-michael-gattozzi.flac",
]
duration = "01:11:28"
publish-date = "Tue, 12 Jan 2021 06:00:00 GMT"
keywords = [
    "rust",
    "programming",
    "technology",
    "serialization",
]

[[episodes]]
title = "002 - Christopher Hunt"
url = "https://jamesmunns.com/podcast/002-chris/"
description = """
James chats with Christopher Hunt to discuss programming languages, \
the cost of software abstraction, Bluetooth, and state machines.
"""
subtitle = "James chats with Christopher Hunt"
files = [
    "2021-01-05-christopher-hunt.m4a",
    "2021-01-05-christopher-hunt.mp3",
    "2021-01-05-christopher-hunt.flac",
]
duration = "01:11:47"
publish-date = "Tue, 05 Jan 2021 16:00:00 GMT"
keywords = [
    "rust",
    "programming",
    "technology",
]

[[episodes]]
title = "001 - Lachezar Lechev"
url = "https://jamesmunns.com/podcast/001-lachezar/"
description = """
James chats with Lachezar Lechev to discuss Rust in Avionics, \
drone simulation technologies, and burnout in software development.
"""
subtitle = "James chats with Lachezar Lechev"
files = [
    "2020-12-29-lachezar-lechev.m4a",
    "2020-12-29-lachezar-lechev.mp3",
    "2020-12-29-lachezar-lechev.flac",
]
duration = "00:45:35"
publish-date = "Tue, 29 Dec 2020 19:00:00 GMT"
keywords = [
    "avionics",
    "rust",
    "programming",
    "technology"
]

[[episodes]]
title = "000 - Foreward"
url = "https://jamesmunns.com/podcast/000-foreward/"
description = "James introduces the Chats with James Podcast."
subtitle = "James introduces the Chats with James Podcast."
files = [
    "2020-12-28-introduction.flac",
    "2020-12-28-introduction.mp3",
    "2020-12-28-introduction.m4a",
]
duration = "00:01:13"
publish-date = "Mon, 28 Dec 2020 19:00:00 GMT"
keywords = [
    "rust",
    "programming",
    "technology"
]
